vad:
  sample_rate: 16000
  chunk_samples: 512
  speech_pad_ms: 500  # VAD 检测到语音结束后，额外保留的尾部静音时长（毫秒），以防止切掉句尾的词
  min_silence_duration_ms: 1000 # 定义多长的静音算作一句话的结束（毫秒）
  speech_prefix_ms: 500 # 语音开始前添加的前缀静音时长（毫秒）
  threshold: 0.4      # 梦话场景建议值：对低音量更敏感

stt:
  type: "funasr"  # 指定要使用的 STT 引擎类型。可选值: "dummy", "funasr"
  # whisper: # 示例：未来 Whisper 引擎的配置
  #   model_path: "path/to/your/whisper/model"

storage:
  type: "minio" # 可选值: "local", "minio"
  minio:
    endpoint: "192.168.31.180:9000"
    access_key: "njj"
    secret_key: "Nijiajun@1108"
    bucket_name: "dream-talker"
    secure: false

security:
  # IMPORTANT: Change this to a long, random string for security!
  access_code: "Nijiajun@1108"